---
- name: Installing k3s on kubernetes nodes
  hosts: k8s_secondary
  become: true
  vars_files:
    - ./vault.yml
  tasks:
    - name: Retreive setup from github
      ansible.builtin.git:
        repo: "https://github.com/fredrikjag/homelab.git"
        dest: "/tmp/homelab"

    - name: Make auto-deploy directory
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/server/manifests/
        state: directory
        mode: '0755'

    - name: Make config directory
      ansible.builtin.file:
        path: /etc/rancher/k3s/
        state: directory
        mode: '0755'

    - name: Install k3s on secondary nodes
      ansible.builtin.shell:
        cmd: "curl -sfL https://get.k3s.io | K3S_TOKEN='{{ vault_secret }}' sh -s server --server https://10.254.1.11:6443 --tls-san='{{ tls_san_ip }}' --tls-san='{{ tls_san_hostname }}' --disable='servicelb'"