---
- name: Installing k3s on kubernetes nodes
  hosts: k8s_first
  become: true
  tasks:
    - name: Retreive setup from github
      ansible.builtin.git:
        repo: "https://github.com/fredrikjag/homelab.git"
        dest: "/tmp/homelab"

    - name: Make auto-deploy directory
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/server/manifests/
        state: directory
        mode: '0754'

    - name: Make config directory
      ansible.builtin.file:
        path: /etc/rancher/k3s/
        state: directory
        mode: '0754'

    - name: Move kubeconfig to config directory
      ansible.builtin.file:
        src: "/tmp/homelab/kubernetes/install/secondary-config.yaml"
        dest: "/etc/rancher/k3s/config.yaml"
        state: link
    
    - name: Install k3s on secondary nodes
      ansible.builtin.shell:
        cmd: "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='server' sh -s - --K3S_TOKEN='{{ vault_secret }}' --tls-san='{{ tls_san_ip }}' --tls-san='{{ tls_san_hostname }}' --disable='servicelb' K3S_KUBECONFIG_MODE='644'"